config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from apps.catalog import views as cat_views

urlpatterns = [
    path("djadmin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", cat_views.homepage),
    path("search/", cat_views.search, name="search"),
    path("about/", cat_views.about),
    path("random/", cat_views.random_dataset),
    path("dataset/<int:dataset_id>/", cat_views.dataset_detail, name="dataset-detail"),
]

if settings.DEBUG and not settings.IS_TESTING:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()

apps/catalog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class PublisherKind(models.TextChoices):
    GOV_NATIONAL = "gn", _("Government - National")
    GOV_STATE = "gs", _("Government - State")
    GOV_LOCAL = "gl", _("Government - Local")
    NGO = "ng", _("Non-Governmental Organization")
    ACADEMIC = "ac", _("Academic")


# NOTE: keep sorted & in sync with ingestion.data_models
class FileType(models.TextChoices):
    CSV = "csv", _("CSV")
    FGDB = "fgdb/gdb", _("File Geodatabase")
    GEOJSON = "geojson", _("GeoJSON")
    JSON = "json", _("JSON Object")
    KML = "kml", _("KML (GeoXML)")
    OTHER = "other", _("Other File Type")
    OTHER_GEO = "other-geo", _("Other Geo File Type")
    PARQUET = "parquet", _("Parquet Database")
    SHP = "shp", _("Shapefile")
    SQLITE = "sqlite", _("SQLite Database")
    TSV = "tsv", _("Tab-Separated Values")
    XLS = "xls", _("Excel Spreadsheet")
    XLSX = "xlsx", _("Excel Open XML Spreadsheet")
    XML = "xml", _("XML File")


class TimePeriod(models.TextChoices):
    DECENNIAL = "dc", _("Decennial")  # every 10 years
    QUINQUENNIAL = "qq", _("Quinquennial")  # 5 years
    BIENNIAL = "be", _("Biennial")  # 2 years
    ANNUAL = "an", _("Annual")
    SEMIANNUAL = "sa", _("Semi-Annual")  # 6 months
    QUARTER = "qu", _("Quarterly")
    MONTH = "mo", _("Monthly")
    WEEK = "wk", _("Weekly")
    DAY = "dy", _("Daily")
    OTHER = "ot", _("Other")


class Publisher(models.Model):
    name = models.TextField()
    kind = models.CharField(max_length=2, choices=PublisherKind)

    url = models.URLField(max_length=500)
    mirror = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - {self.kind}"


class Region(models.Model):
    name = models.TextField()
    country_code = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.name} - {self.country_code}"


class TemporalCollection(models.Model):
    """
    Represents a collection of DataSet that approximately represents the
    same data across different time periods.

    Example: Quarterly Traffic Tickets or Annual Geographic Boundaries.
    """

    name = models.TextField()
    period = models.CharField(max_length=2, choices=TimePeriod)

    def __str__(self):
        return f"{self.name} - {self.period}"


class CuratedCollection(models.Model):
    """
    Represents a collection of DataSet that are related in some (non-temporal)
    manner.

    Example: "Midwestern Agriculture" or "Solar Energy"
    """

    name = models.TextField()

    def __str__(self):
        return self.name


class IdentifierKind(models.Model):
    """
    A kind of identifier common across data sets.

    Example: FIPS, ISO-3166
    """

    kind = models.TextField()

    def __str__(self):
        return self.kind


class Identifier(models.Model):
    """
    An instance of a known identifier of an IdentifierKind.

    Example: 06 (FIPS), DK (ISO)
    """

    identifier_kind = models.ForeignKey(IdentifierKind, on_delete=models.CASCADE)
    identifier = models.TextField()

    def __str__(self):
        return f"{self.identifier} ({self.identifier_kind})"


class Crosswalk(models.Model):
    """
    A relationship between two identifiers.
    """

    primary = models.ForeignKey(Identifier, on_delete=models.CASCADE, related_name="crosswalks")
    secondary = models.ForeignKey(Identifier, on_delete=models.CASCADE, related_name=None)

    def __str__(self):
        return f"Crosswalk: {self.primary} - {self.secondary}"


class DataSet(models.Model):
    """
    Fundamental unit of the catalog, a single data set.

    This will correspond 1:1 to upstream concepts of a dataset,
    typically a release of data with a common metadata.

    TODO: some data sets are static, but some may update periodically
          without creating a new release
    """

    name = models.CharField(max_length=500)
    description = models.TextField(blank=True)

    # define the time range covered by the data (if known)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    upstream_upload_time = models.DateTimeField()
    publisher = models.ForeignKey(Publisher, on_delete=models.PROTECT)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)

    source_url = models.URLField(max_length=500)
    upstream_id = models.CharField(max_length=100)
    license = models.CharField(max_length=100)

    # -- fields below this are populated after initial ingestion --
    temporal_collection = models.ForeignKey(
        TemporalCollection,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="datasets",
    )
    curated_collections = models.ManyToManyField(
        CuratedCollection, blank=True, related_name="datasets"
    )
    quality_score = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    scraper = models.TextField(null=True)

    identifier_kinds = models.ManyToManyField(IdentifierKind, blank=True, related_name="datasets")

    def __str__(self):
        return f"{self.name}: {self.start_date}-{self.end_date}"


class DataSetFile(models.Model):
    """
    A downloadable artifact associated with a dataset.

    Some datasets may consist of multiple related files, and others may
    be offered in multiple formats.
    """

    dataset = models.ForeignKey(DataSet, on_delete=models.CASCADE, related_name="files")
    original_url = models.URLField(max_length=500)
    url = models.URLField(max_length=500)
    mirrored_url = models.URLField(max_length=500, null=True)
    last_mirrored = models.DateTimeField(null=True)
    file_type = models.CharField(choices=FileType)
    file_size_mb = models.IntegerField()  # file size in megabytes

    def file_type_and_size(self):
        """if size is 0, omit"""
        if self.file_size_mb:
            return f"{self.dataset.name} File: {self.file_type}, {self.file_size_mb} MB"
        else:
            return f"{self.dataset.name} File: {self.file_type}"

    def __str__(self):
        return f"{self.dataset.name} File: {self.file_type}, {self.file_size_mb} MB"


# class GeoProjection(?)

templates/about.html
{% extends "base.html" %}

{% block content %}
<h2 class="title">About</h2>

<h3 class="title is-4">Data</h3>

<h3 class="title is-4">Terminology</h3>

<h3 class="title is-4">Team</h3>

<h3 class="title is-4">Contributing</h3>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="main-content">
      <nav class="navbar" role="navigation">
          <div class="navbar-brand">
            <a class="navbar-item" href="/">
            <h2 class="title is-4">public data explorer</h2>
            </a>
          </div>
        <div class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" a href="/search/">
                  <span class="icon"><i class="fas fa-search"></i></span>
                  Search
                </a>
                <a class="navbar-item" a href="/random/">
                  <span class="icon"><i class="fas fa-dice"></i></span>
                  Random
                </a>
                <a class="navbar-item" a href="/about/">
                  About
                </a>
                {% if request.user.is_authenticated %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <span class="icon"><i class="fas fa-user"></i></span>
                        <span>{{ request.user }}</span>
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">Saved Datasets</a>
                        <a class="navbar-item">Profile</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="/accounts/logout/">Sign Out</a>
                    </div>
                </div>
                {% else %}
                <a class="navbar-item" href="/accounts/signup/">Sign Up</a>
                <a class="navbar-item" href="/accounts/login/">Sign In</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="content-body">
      <div class="container">
      {% block content%}
      {% endblock %}
      </div>
    </div>

    <footer class="footer">
      <div class="content has-text-centered">
      <p>
      <strong>public data explorer</strong> is a project developed by <a href="https://capp.uchicago.edu/">MSCAPP</a> students.
      <br>
      This site is a directory of public data sets. We can not make any guarantees about the integrity of indexed data catalogs.
      </p>
      <p>
        <a href="https://github.com/uchicago-mscapp-projects/public-data-portal">
        contribute via GitHub
        <span class="icon"><i class="fa-brands fa-github"></i></span>
        </a>
      </p>
      </div>
    </footer>

  </div>
  </body>
</html>

templates/dataset_detail.html
{% extends "base.html" %}

{% block title %}
  Public Data Portal | {{ ds.name }} - {{ ds.publisher }}
{% endblock %}

{% block content %}

  <div class="block" id="header">
    <h1 class="title">{{ ds.name }}</h1>

    <!-- put subtitle & buttons side-by-side -->
    <div class="columns">
      <div class="column is-half">
        <p>a dataset published by</p><h2 class="subtitle">{{ds.publisher.name }} | {{ ds.region.name }} | {{ ds.region.country_code|upper }}</h2>
      </div>
      <div class="block column is-half has-text-right">
        <button class="button is-primary" aria-haspopup="true" aria-controls="dropdown-menu">
          <span class="icon">
            <i class="fas fa-star" aria-hidden="true"></i>
          </span>
          <span>Save</span>
        </button>
        {# Download dropdown menu #}
          <div class="dropdown is-hoverable">
            <div class="dropdown-trigger">
              <button class="button is-success" aria-haspopup="true" aria-controls="dropdown-menu">
                <span>Download</span>
                <span class="icon is-small">
                  <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                {% for file in files %}
                  <a href="{{ file.url }}" target="_blank" class="dropdown-item">{{ file.get_file_type_display }} {% if file.file_size_mb %} ({{ file.file_size_mb }}MB) {% endif %}</a>
                {% endfor %}
              </div>
            </div>
        </div>
      </div>

    </div>
  </div>

  {% if ds.temporal_collection %}
  <div class="box" id="temporal-collection">
    <p>This dataset is part of the <a href="#">{{ ds.temporal_collection}}</a> collection.</p>
  </div>
  {% endif %}

  <div class="block" id="quality-score">
    {% if ds.quality_score == -1 %}
    <p>Quality Score: quality score not available</p>
    {% else %}
    <p>Quality Score: {{ ds.quality_score }}</p>
    {% endif %}
  </div>

<div class="block">
  <span class="tag"> Tag label </span>
  {% for tag in tags %}
    <span class="tag"> {{ tag }} </span>
  {% endfor %}
</div>

{# tabs for details/metadata/ugc/collections; reorg layout later #}
<div>
  <div class="tabs is-boxed">
    <ul>
      {% for tab in tabs %}
        <li data-tab="{{ tab.id }}" class="{% if forloop.first %}is-active{% endif %}">
          <a>{{ tab.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>

  <div id="tab-content">
    <div class="tab-pane is-active" id="details">
      <div class="block">
        <p><strong>Source URL:</strong> <a class="source-link" href="{{ ds.source_url }}">{{ ds.source_url }}</a></p>
        <p><strong title="Timestamp on data provided by publisher..">Published:</strong> {{ ds.upstream_upload_time|date:"Y-m-d" }}</p>
        <p><strong>Publisher</strong>: {{ ds.publisher.name }} ({{ds.publisher.get_kind_display}})</p>
        <p><strong>Region</strong>: {{ ds.region.name }} | {{ ds.region.country_code|upper }}</p>
        <p><strong title="Last time this dataset was updated by our scrapers.">Last scraped:</strong> {{ ds.updated_at|date:"Y-m-d" }}</p>
        <p><strong title="First time this dataset was seen by our scrapers. ">First seen:</strong> {{ ds.created_at|date:"Y-m-d" }}</p>
      </div>
      <div class="block">
        <h4 class="title is-4">Description</h4>
        <p>{{ ds.description }}</p>
      </div>
    </div>
    <div class="tab-pane" id="comments">
      <p>Comments and other UGC can go here?</p>
    </div>
    <div class="tab-pane" id="collections">
      {% if ds.temporal_collection %}
        <div class="button is-info"><a href="#">{{ ds.temporal_collection }}</a></div>
      {% endif %}
      {% for collection in collections %}
        <div class="button"><a href="#">{{ collection.name }}</a></div>
      {% endfor %}
    </div>
  </div>


  <hr>

  <button class="button is-danger" aria-haspopup="true" aria-controls="dropdown-menu">
    <span class="icon">
      <i class="fas fa-warning" aria-hidden="true"></i>
    </span>
    <span>Report Data Issue</span>
  </button>

</div>

{# JS in html file for testing; abstract out later #}
<style>
  .tab-pane {
    display: none;
  }
  .tab-pane.is-active {
    display: block;
  }
  a { color: inherit; }
</style>

<script>
document.addEventListener("DOMContentLoaded", () => {
  const tabs = document.querySelectorAll(".tabs ul li");
  const panes = document.querySelectorAll(".tab-pane");

  tabs.forEach(tab => {
    tab.addEventListener("click", () => {
      const target = tab.dataset.tab;

      // remove is-active from all tabs and panes
      tabs.forEach(t => t.classList.remove("is-active"));
      panes.forEach(p => p.classList.remove("is-active"));

      // add is-active to the clicked tab and its pane
      tab.classList.add("is-active");
      document.getElementById(target).classList.add("is-active");
    });
  });
});
</script>

{% endblock %}

templates/homepage.html
{% extends "base.html" %}

{% block title %}
  Public Data Portal
{% endblock %}

{% block content %}

<div class="block" id="search box">
    <form action="{% url 'search' %}" method="get">
        <div class="field has-addons">
            <div class="control has-icons-left is-expanded">
                <input class="input" type="text" placeholder="Search..." name="query" id="searchInput" value={{keyword}}>
                <span class="icon is-small is-left">
                    <i class="fas fa-search"></i> <!-- Font Awesome search icon -->
                </span>
            </div>
            <div class="control">
                <button class="button is-info" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>

<section class="section">
    <div class="container">
        <div id="greeting">
            <h2>Hello {{ name }}! Our site currently hosts...</h2>
        </div>

        <div class="stat-box">
            <h3 class="title">{{ num_datasets }}</h3>
            <span class="subtitle"> datasets</span>
        </div>

        <div class="stat-box">
            <h3 class="title">{{ num_publishers }}</h3>
            <span class="subtitle"> publishers</span>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h3 class="title">Recent Datasets</h3>
                {% for dset in recent_datasets %}
                <div class="box">
                    <p>
                        <b>
                            <a href="{% url 'dataset-detail' dset.id %}">{{ dset.name }}</a>
                        </b>
                    </p>
                    <p>Last updated: {{ dset.upstream_upload_time|date:"F j, Y, g:i a" }}</p>
                </div>
                {% endfor %}
            </div>
            <div class="column">
                <h3 class="title">Featured Publishers</h3>
                {% for pub in featured_publishers %}
                <div class="box">
                    <p>
                        <b>
                            <a href="{{ pub.url }}">{{ pub.name }}</a>
                        </b>
                    </p>
                    <p>Kind: {{ pub.kind }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% comment %}
This template is meant as a small demonstration of how we'll
build out templates & views.

base.html sets up a simple HTML template with Bulma installed.

We'll override the title & content blocks to build our initial index page.
{% endcomment %}


{% block title %}
  Public Data Portal
{% endblock %}

{% block content %}
  {% comment %}
  At this point don't worry too much about the HTML!

  We'll focus on two things for now, content that we want to group together on the page
  will go into a <div>, and we can use components & styles from Bulma where we'd like.

  Below we make a few sections, one for displaying a temporary greeting and a second
  box that will contain the number of datasets.
  {% endcomment %}

  <div id="greeting"> {# in HTML id is optional, naming the div for future reference #}
  <h2>Hello {{ name }}!</h2>
  </div>

  <div class="stat-box"> {# a class is like an ID but can apply to multiple (similar) items #}
    {# these classes are defined by Bulma, and will style the content #}
    <h3 class="title">{{ num_datasets }}</h3>
    <span class="subtitle"> datasets</span>
  </div>

  <div class="stat-box"> {# a class is like an ID but can apply to multiple (similar) items #}
    {# these classes are defined by Bulma, and will style the content #}
    <h3 class="title">{{ num_publishers }}</h3>
    <span class="subtitle"> publishers</span>
  </div>
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block title %}
  Public Data Portal
{% endblock %}

{% block content %}

  <div class="block" id="search box">
    <form action="" method="get">
      <div class="field has-addons">
    <div class="control has-icons-left is-expanded">
      <input class="input" type="text" placeholder="Search..." name="query" id="searchInput" value="{{keyword}}">
      <span class="icon is-small is-left">
        <i class="fas fa-search"></i> <!-- Font Awesome search icon -->
      </span>
    </div>
    <div class="control">
      <button class="button is-info" type="submit">Search</button>
    </div>
  </div>
    </form>
  </div>


<!-- <option value="AllFields">All Fields</option>
<option value="LastUpdated">Last Updated</option> sort, not filter
<option value="QualityScore">Quality Score</option> sort, not filter

GOV_NATIONAL = "gn", _("Government - National")
    GOV_STATE = "gs", _("Government - State")
    GOV_LOCAL = "gl", _("Government - Local")
    NGO = "ng", _("Non-Governmental Organization")
    ACADEMIC = "ac", _("Academic")
-->
<!-- Advanced search goes here -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
      const toggleButton = document.getElementById('advsearchtrigger');
      const collapsibleContent = document.getElementById('advsearchpanel');

      toggleButton.addEventListener('click', function() {
        if (collapsibleContent.style.display === 'none') {
          collapsibleContent.style.display = 'block';
        } else {
          collapsibleContent.style.display = 'none';
        }
      });
    });
</script>

<div class="block">
<button id="advsearchtrigger" class="button is-primary" type="button">Advanced Search</button>
<div id="advsearchpanel" class=box style="display: none;">
    <form action="" method="get">
      <!-- <h2>Advanced Search</h2> -->
       <input id="advsearchInput" name="query" type="hidden" value={{keyword}}>
        <div class="columns">
            <div class="column">
                <div class="block">
                    <label>Publisher Name:</label>
                    <input class="input" type="text" placeholder="Publisher Name..." name="PublisherName" id="PublisherName" value="{{ parameters.PublisherName }}">
                </div>
                <!-- <div class="block">
                    <label>Collection Name:</label>
                    <input class="input" type="text" placeholder="Collection Name..." name="CollectionName" id="CollectionName">
                </div> -->
            </div>
            <div class="column">
                <fieldset>
                  <p>
                    <label for="pubtype">Publisher Type:</label>
                    <div class="select is-multiple">
                    <select name="pubtype" id="pubtype" multiple size="5">
                        <option value="gn"
                            {% if gn in parameters.pubtype %}
                            selected {%endif%}>National Government
                        </option>
                        <option value="gs"
                            {% if gs in parameters.pubtype %}
                            selected {%endif%}>State or Regional Government
                        </option>
                        <option value="gl"
                            {% if gl in parameters.pubtype %}
                            selected {%endif%}>Local Government
                        </option>
                        <option value="ng"
                            {% if ng in parameters.pubtype %}
                            selected {%endif%}>Non-Governmental Organization
                        </option>
                        <option value="ac"
                            {% if ac in parameters.pubtype %}
                            selected {%endif%}>Academic
                        </option>
                    </select>
                  </p>
                </fieldset>
            </div>
        <div class="column">
            <fieldset>
                  <p>
                    <label for="region">Geographic Region:</label>
                    <div class="select is-multiple">
                    <select name="region" id="region" multiple size="4">
                    {% for geo in geographies %}
                        <option value={{geo}}
                            {% if geo in parameters.region %}
                            selected {%endif%}>{{geo}}
                        </option>
                    {% endfor %}
                    </select>
                </p>
            </fieldset>
        </div>
        <div class="column">
            <fieldset>
            <p>
                <label for="filetype">File Type:</label>
                <div class="select is-multiple">
                <select name="filetype" id="filetype" multiple size="4">
                    {% for type in filetypes %}
                        <option value={{type}}
                            {% if type in parameters.filetype %}
                            selected {%endif%}>{{type}}
                        </option>
                    {% endfor %}
                </select>
                </div>
            </p>
            </fieldset>
        </div>
            </div>
          <p>
        <div class="adv-submit">
        <input class="button is-primary is-small" type="reset" value="Clear">
        <input class="button is-info is-small" type="submit" value="Search">
        </div>
      </p>

    </form>
</div>
</div>

  <div class="block">
  <div id="search start">
  <h2>Search Results:</h2>
  </div>

  <div id="n_results"> {# in HTML id is optional, naming the div for future reference #}
  <h2>{{n_results}} results found for <b>datasets</b> containing the keyword "{{keyword}}".
  </h2>
  </div>
  </div>

  {% for dset in page %}
  <div class="box">
    <p>
        <b>
            <a href="http://127.0.0.1:8000/dataset/{{dset.pk}}/">{{ dset.name }}</a>
        </b>
    </p>
    <p>Published by {{ dset.publisher }}</p>
    <p>Last updated {{ dset.upstream_upload_time|date:"F j, Y" }}</p>
  </div>
  {% endfor %}

  <div class="field">
    <label class="label">Results per page:</label>
    <div class="control">
      <div class="select">
        <select id="resultsPerPage">
          <option value="10">10</option>
          <li>
            <a href="?limit=25&page=1" class="dropdown-item"> 10 </a>
          </li>
          <option value="25">25</option>
            <a href="?limit=25&page={{ page.number }}" class="dropdown-item"> This is a link </a>
          <option value="50">50</option>
            <a href="?limit=50&page={{ page.number }}" class="dropdown-item"> This is a link </a>
          <option value="100">100</option>
            <a href="?limit=100&page={{ page.number }}" class="dropdown-item"> This is a link </a>
        </select>
      </div>
    </div>
  </div>

  <nav class="pagination" role="navigation" aria-label="pagination">
  {% if page.has_previous %}
    <a href="{{ uri }}&page={{ page.previous_page_number }}" class="pagination-previous">Previous</a>
  {% endif %}
  {% if page.has_next %}
    <a href="{{ uri }}&page={{ page.next_page_number }}" class="pagination-next">Next page</a>
  {% endif %}
  <ul class="pagination-list">
    {% if page.has_previous %}
    <li>
      <a href="{{ uri }}&page=1" class="pagination-link" aria-label="Goto page 1">1</a>
    </li>
      {% if page.number > 2 %}
        <li>
        <span class="pagination-ellipsis">&hellip;</span>
        </li>
        <li>
        <a href="{{ uri }}&page={{ page.previous_page_number }}" class="pagination-link" aria-label="Goto previous page">{{page.previous_page_number}}</a>
        </li>
      {% endif %}
    {% endif %}
    <li>
      <a
        class="pagination-link is-current"
        aria-label="Page {{page_num}}"
        aria-current="page"
        >{{page.number}}</a
      >
    </li>
    {% if page.has_next %}
      {% if page.paginator.num_pages > page.next_page_number %}
        <li>
        <a href="{{ uri }}&page={{ page.next_page_number }}" class="pagination-link" aria-label="Goto page {{page.next_page_number}}">{{page.next_page_number}}</a>
        </li>
        <li>
        <span class="pagination-ellipsis">&hellip;</span>
        </li>
      {% endif %}
    <li>
      <a href="{{ uri }}&page={{ page.paginator.num_pages }}" class="pagination-link" aria-label="Goto last page">{{page.paginator.num_pages}}</a>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}